version: "3.8"
services:
  dev:
    build:
      #context: .
      dockerfile: startup/Dockerfile
    env_file:
      - startup/dev.env
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
      - ../app:/tf-eks
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro
    working_dir: /tf-eks
   # entrypoint: 
   #  - dev/app/startup/init.sh